---
title: "Theory and Analysis of Congressional Politics"
subtitle: "P SC 3143: U.S. Congress"
author: "Nathan Barron"
format: revealjs
execute:
  freeze: auto
---

```{r}
library(tidyverse)
library(ggforce)
```

# Actor with unidimensional preference

---

```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -5, y = -.15,xend = -5, yend = .15)) + 
  annotate("text", x = -5, y = -.25, label = "Actor A") +
  geom_segment(aes(x = 0, y = -.15,xend = 0, yend = .15)) + 
  annotate("text", x = 0, y = -.25, label = "Policy A") +
  geom_segment(aes(x = 3.5, y = -.15,xend = 3.5, yend = .15)) +
  annotate("text", x = 3.5, y = -.25, label = "Status Quo") +
  geom_segment(aes(x = 6, y = -.15,xend = 6, yend = .15)) +
  annotate("text", x = 6, y = -.25, label = "Policy B") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```

---

```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -5, y = -.15,xend = -5, yend = .15)) + 
  annotate("text", x = -5, y = -.25, label = "Actor A") +
  geom_segment(aes(x = 0, y = -.15,xend = 0, yend = .15)) + 
  annotate("text", x = 0, y = -.25, label = "Policy A") +
  geom_segment(aes(x = 3.5, y = -.15,xend = 3.5, yend = .15)) +
  annotate("text", x = 3.5, y = -.25, label = "Status Quo") +
  geom_segment(aes(x = 6, y = -.15,xend = 6, yend = .15)) +
  annotate("text", x = 6, y = -.25, label = "Policy B") +
  geom_rect(aes(xmin=-9.5, xmax=3.499999, ymin=-.05, ymax = .05), fill = "forestgreen", alpha =.25) +
  geom_rect(aes(xmin=3.5, xmax=10, ymin=-.05, ymax = .05), fill = "red", alpha =.25) +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```

---


```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -5, y = -.15,xend = -5, yend = .15)) + 
  annotate("text", x = -5, y = -.25, label = "Status Quo") +
  geom_segment(aes(x = 0, y = -.15,xend = 0, yend = .15)) + 
  annotate("text", x = 0, y = -.25, label = "Actor A") +
  geom_segment(aes(x = 3.5, y = -.15,xend = 3.5, yend = .15)) +
  annotate("text", x = 3.5, y = -.25, label = "Policy C") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```


---

```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -5, y = -.15,xend = -5, yend = .15)) + 
  annotate("text", x = -5, y = -.25, label = "Status Quo") +
  geom_segment(aes(x = 0, y = -.15,xend = 0, yend = .15)) + 
  annotate("text", x = 0, y = -.25, label = "Actor A") +
  geom_segment(aes(x = 3.5, y = -.15,xend = 3.5, yend = .15)) +
  annotate("text", x = 3.5, y = -.25, label = "Policy C") +
  geom_rect(aes(xmin=-5, xmax=5, ymin=-.05, ymax = .05), fill = "forestgreen", alpha =.25) +
  geom_rect(aes(xmin=-10, xmax=-5, ymin=-.05, ymax = .05), fill = "red", alpha =.25) +
  geom_rect(aes(xmin=5, xmax=10, ymin=-.05, ymax = .05), fill = "red", alpha =.25) +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```



# Actor with unidimensional utility

---


```{r}
x <- seq(-10, 10, length.out = 1000)
yd <-  -3*(x + 5)^2 + 25
ggplot() +
  geom_vline(aes(xintercept = -5), color = 'grey30', linetype = "dashed") +
  geom_line(aes(x = x, y = yd), color = "blue", linewidth = 1) +
  geom_point(aes(x=-5, y=max(yd)), color = "blue", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yd), fill = "blue", alpha = .15)+
  labs(title = "Preference Utility Curve for a Single Actor in Unidimensional Space",
       x = "Preference Dimension",
       y = "Preference Level\n(Utility)") +
  scale_y_continuous(limit = c(0,25)) + 
  theme_minimal()
```


---


```{r}
ggplot() +
  geom_vline(aes(xintercept = -5), color = 'grey30', linetype = "dashed") +
  geom_line(aes(x = x, y = yd), color = "blue", linewidth = 1) +
  geom_point(aes(x=-5, y=max(yd)), color = "blue", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yd), fill = "blue", alpha = .15)+
  geom_vline(aes(xintercept = 1), color = 'black') +
  geom_vline(aes(xintercept = -1.5), color = 'red', linetype = "dotted", size = 1) +
  geom_vline(aes(xintercept = -3), color = 'forestgreen', linetype = "dotted", size = 1) +
  geom_rect(aes(xmin = 2, xmax = 8, ymin=12, ymax = 23), fill = "grey80", alpha = .5) + 
  annotate("text", x = 5, y = 20, label = "Status Quo = 1", color = "black", size = 5) +
  annotate("text", x = 5, y = 17.5, label = "Policy A = -1.5", color = "red", size = 5) +
  annotate("text", x = 5, y = 15, label = "Policy B = -3", color = "forestgreen", size = 5) +
  labs(title = "Preference Utility Curve for a Single Actor in Unidimensional Space",
       x = "Preference Dimension",
       y = "Preference Level\n(Utility)") +
  scale_y_continuous(limit = c(0,25)) + 
  theme_minimal()
```


# Actor with unidimensional preference

---

```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -7, y = -.15,xend = -7, yend = .15)) + 
  annotate("text", x = -7, y = -.25, label = "Actor A") +
  geom_segment(aes(x = -4, y = -.15,xend = -4, yend = .15)) + 
  annotate("text", x = -4, y = -.25, label = "Actor B") +
  geom_segment(aes(x = -1, y = -.15,xend = -1, yend = .15)) + 
  annotate("text", x = -1, y = -.25, label = "Actor C") +
  geom_segment(aes(x = 2, y = -.15,xend = 2, yend = .15)) + 
  annotate("text", x = 2, y = -.25, label = "Actor D") +
  geom_segment(aes(x = 5, y = -.15,xend = 5, yend = .15)) + 
  annotate("text", x = 5, y = -.25, label = "Actor E") +
  geom_segment(aes(x = 0.5, y = -.15,xend = 0.5, yend = .15), color = "blue") + 
  annotate("text", x = 0.5, y = .25, label = "Status Quo", color = "blue") +
  geom_segment(aes(x = 3, y = -.15,xend = 3, yend = .15), color = "red") + 
  annotate("text", x = 3, y = .25, label = "Policy D", color = "red") +
  geom_segment(aes(x = -2.4, y = -.15,xend = -2.4, yend = .15), color = "red") + 
  annotate("text", x = -2.4, y = .25, label = "Policy E", color = "red") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```


---


```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -7, y = -.15,xend = -7, yend = .15)) + 
  annotate("text", x = -7, y = -.25, label = "Actor A") +
  geom_segment(aes(x = -4, y = -.15,xend = -4, yend = .15)) + 
  annotate("text", x = -4, y = -.25, label = "Actor B") +
  geom_segment(aes(x = 0.5, y = -.15,xend = 0.5, yend = .15), color = "blue") + 
  annotate("text", x = 0.5, y = .25, label = "Status Quo", color = "blue") +
  geom_segment(aes(x = 3, y = -.15,xend = 3, yend = .15), color = "red") + 
  annotate("text", x = 3, y = .25, label = "Policy D", color = "red") +
  geom_segment(aes(x = -2.4, y = -.15,xend = -2.4, yend = .15), color = "red") + 
  annotate("text", x = -2.4, y = .25, label = "Policy E", color = "red") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```



---


```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = 5, y = -.15,xend = 5, yend = .15)) + 
  annotate("text", x = 5, y = -.25, label = "Actor E") +
  geom_segment(aes(x = 0.5, y = -.15,xend = 0.5, yend = .15), color = "blue") + 
  annotate("text", x = 0.5, y = .25, label = "Status Quo", color = "blue") +
  geom_segment(aes(x = 3, y = -.15,xend = 3, yend = .15), color = "red") + 
  annotate("text", x = 3, y = .25, label = "Policy D", color = "red") +
  geom_segment(aes(x = -2.4, y = -.15,xend = -2.4, yend = .15), color = "red") + 
  annotate("text", x = -2.4, y = .25, label = "Policy E", color = "red") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```



---


```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = 2, y = -.15,xend = 2, yend = .15)) + 
  annotate("text", x = 2, y = -.25, label = "Actor D") +
  geom_segment(aes(x = 0.5, y = -.15,xend = 0.5, yend = .15), color = "blue") + 
  annotate("text", x = 0.5, y = .25, label = "Status Quo", color = "blue") +
  geom_segment(aes(x = 3, y = -.15,xend = 3, yend = .15), color = "red") + 
  annotate("text", x = 3, y = .25, label = "Policy D", color = "red") +
  geom_segment(aes(x = -2.4, y = -.15,xend = -2.4, yend = .15), color = "red") + 
  annotate("text", x = -2.4, y = .25, label = "Policy E", color = "red") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```

---


```{r}

ggplot() + 
  geom_segment(
    aes(x = -10, y = 0, xend = 10, yend = 0), 
    arrow = arrow(angle = 30, length = unit(.25, "cm"), ends = "both", type = "closed")
  ) + 
  geom_segment(aes(x = -1, y = -.15,xend = -1, yend = .15)) + 
  annotate("text", x = -1, y = -.25, label = "Actor C") +
  geom_segment(aes(x = 0.5, y = -.15,xend = 0.5, yend = .15), color = "blue") + 
  annotate("text", x = 0.5, y = .25, label = "Status Quo", color = "blue") +
  geom_segment(aes(x = 3, y = -.15,xend = 3, yend = .15), color = "red") + 
  annotate("text", x = 3, y = .25, label = "Policy D", color = "red") +
  geom_segment(aes(x = -2.4, y = -.15,xend = -2.4, yend = .15), color = "red") + 
  annotate("text", x = -2.4, y = .25, label = "Policy E", color = "red") +
  scale_x_continuous(limits = c(-10, 10)) + 
  scale_y_continuous(limits = c(-1,1)) + 
  theme_void()

```





# Actors with unidimensional utility


---

```{r}
yr <- -3*(x -5)^2 + 25
ggplot() +
  geom_line(aes(x = x, y = yd), color = "blue", linewidth = 1) +
  geom_point(aes(x=-5, y=max(yd)), color = "blue", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yd), fill = "blue", alpha = .15)+
  geom_line(aes(x = x, y = yr), color = "red", linewidth = 1) +
  geom_point(aes(x=5, y=max(yr)), color = "red", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yr), fill = "red", alpha = .15)+
  labs(title = "Preference Utility Curves for a Multiple Actors in Unidimensional Space",
       x = "Preference Dimension",
       y = "Preference Level\n(Utility)") +
  scale_y_continuous(limit = c(0,25)) + 
  theme_minimal()
```


---

```{r}
yi <- -1/2*(x)^2 + 10
ggplot() +
  geom_line(aes(x = x, y = yd), color = "blue", linewidth = 1) +
  geom_point(aes(x=-5, y=max(yd)), color = "blue", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yd), fill = "blue", alpha = .15)+
  geom_line(aes(x = x, y = yr), color = "red", linewidth = 1) +
  geom_point(aes(x=5, y=max(yr)), color = "red", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yr), fill = "red", alpha = .15)+
  geom_line(aes(x = x, y = yi), color = "purple", linewidth = 1) +
  geom_point(aes(x=0, y=max(yi)), color = "purple", size = 3) +
  geom_ribbon(aes(x = x, y = yd,ymin=0, ymax = yi), fill = "purple", alpha = .15)+
  labs(title = "Preference Utility Curves for a Multiple Actors in Unidimensional Space",
       x = "Preference Dimension",
       y = "Preference Level\n(Utility)") +
  scale_y_continuous(limit = c(0,25)) + 
  theme_minimal()
```




# Actors with multidimensional preferences

---

```{r}
ggplot() +
  geom_point(aes(x = -5, y = 2), color = "red", size = 4) + # Voter A
  geom_point(aes(x = 3, y = 1), color = "blue", size = 4) + # Voter B
  geom_point(aes(x = 2, y = 1), color = "forestgreen", size = 4) + # Voter C
  geom_point(aes(x = -2, y = 4), color = "orange", size = 4) + # Voter B
  geom_point(aes(x = 0, y = 0), color = "darkorchid3", size = 4) + # Voter C
  scale_x_continuous(limits = c(-7,7)) + 
  scale_y_continuous(limits = c(-5,5)) + 
  labs(title = "Preferences with Multiple Actors in Multidimensional Space", 
       x = "Preference Dimension 1",
       y = "Preference Dimension 2") + 
  theme_minimal()
```


---

```{r}
ggplot() +
  geom_point(aes(x = -5, y = 2), color = "red", size = 4) + # Voter A
  geom_point(aes(x = 3, y = 1), color = "blue", size = 4) + # Voter B
  geom_point(aes(x = 2, y = 1), color = "forestgreen", size = 4) + # Voter C
  geom_point(aes(x = -2, y = 4), color = "orange", size = 4) + # Voter B
  geom_point(aes(x = 0, y = 0), color = "darkorchid3", size = 4) + # Voter C
  geom_point(aes(x = -0.4, y = 2), color = "black", size = 6) +
  annotate("text", x = 2, y = 2, size = 5.5,label = "Geometric Mean") + 
  scale_x_continuous(limits = c(-7,7)) + 
  scale_y_continuous(limits = c(-5,5)) + 
  labs(title = "Preferences with Multiple Actors in Multidimensional Space", 
       x = "Preference Dimension 1",
       y = "Preference Dimension 2") + 
  theme_minimal()
```


---


```{r}
ggplot() +
  geom_point(aes(x = -5, y = 2), color = "red", size = 3) + # Voter A
  geom_point(aes(x = 3, y = 1), color = "blue", size = 3) + # Voter B
  geom_point(aes(x = 2, y = 1), color = "forestgreen", size = 3) + # Voter C
  geom_point(aes(x = -2, y = 4), color = "orange", size = 3) + # Voter B
  geom_point(aes(x = 0, y = 0), color = "darkorchid3", size = 3) + # Voter C
  scale_x_continuous(limits = c(-15,15)) + 
  scale_y_continuous(limits = c(-10, 10)) + 
  labs(title = "Preference Utility with Multiple Actors in Multidimensional Space", 
       x = "Preference Dimension 1",
       y = "Preference Dimension 2") + 
  theme_minimal()
```



# Actors with multidimensional utility

---

```{r}
ggplot() +
  geom_ellipse(aes(x0 = -5, y0 = 2, a = 10, b = 3, angle = pi/4), color = "red",  linewidth = 1, fill = "red", alpha = .15) + # Indifference curve for C
  geom_ellipse(aes(x0 = 3, y0 = 1, a = 5, b = 1, angle = -pi/3), color = "blue", linewidth = 1, fill = "blue", alpha = .15) + # Indifference curve for B
  geom_ellipse(aes(x0 = 2, y0 = 1, a = 4, b = 1, angle = -pi/3), color = "forestgreen", linewidth = 1, fill = "forestgreen", alpha = .15) + # Indifference curve for C
  geom_ellipse(aes(x0 = -2, y0 = 4, a = 12, b = 1, angle = 0), color = "orange", linewidth = 1, fill = "orange", alpha = .15) + # Indifference curve for B
  geom_ellipse(aes(x0 = 0, y0 = 0, a = 4, b = 1, angle = -pi/8), color = "darkorchid3", linewidth = 1, fill = "darkorchid3", alpha = .15) + 
  geom_point(aes(x = -5, y = 2), color = "red", size = 3) + # Voter A
  geom_point(aes(x = 3, y = 1), color = "blue", size = 3) + # Voter B
  geom_point(aes(x = 2, y = 1), color = "forestgreen", size = 3) + # Voter C
  geom_point(aes(x = -2, y = 4), color = "orange", size = 3) + # Voter B
  geom_point(aes(x = 0, y = 0), color = "darkorchid3", size = 3) + # Voter C
  scale_x_continuous(limits = c(-15,15)) + 
  scale_y_continuous(limits = c(-10, 10)) + 
  labs(title = "Preference Utility with Multiple Actors in Multidimensional Space", 
       x = "Preference Dimension 1",
       y = "Preference Dimension 2") + 
  theme_minimal()
```


---


```{r}
ggplot() +
  geom_ellipse(aes(x0 = -5, y0 = 2, a = 10, b = 3, angle = pi/4), color = "red",  linewidth = 1, fill = "red", alpha = .15) + # Indifference curve for C
  geom_ellipse(aes(x0 = 3, y0 = 1, a = 5, b = 1, angle = -pi/3), color = "blue", linewidth = 1, fill = "blue", alpha = .15) + # Indifference curve for B
  geom_ellipse(aes(x0 = 2, y0 = 1, a = 4, b = 1, angle = -pi/3), color = "forestgreen", linewidth = 1, fill = "forestgreen", alpha = .15) + # Indifference curve for C
  geom_ellipse(aes(x0 = -2, y0 = 4, a = 12, b = 1, angle = 0), color = "orange", linewidth = 1, fill = "orange", alpha = .15) + # Indifference curve for B
  geom_ellipse(aes(x0 = 0, y0 = 0, a = 4, b = 1, angle = -pi/8), color = "darkorchid3", linewidth = 1, fill = "darkorchid3", alpha = .15) + 
  geom_point(aes(x = -5, y = 2), color = "red", size = 3) + # Voter A
  geom_point(aes(x = 3, y = 1), color = "blue", size = 3) + # Voter B
  geom_point(aes(x = 2, y = 1), color = "forestgreen", size = 3) + # Voter C
  geom_point(aes(x = -2, y = 4), color = "orange", size = 3) + # Voter B
  geom_point(aes(x = 0, y = 0), color = "darkorchid3", size = 3) + # Voter C
  geom_point(aes(x = -0.4, y = 2), color = "black", size = 4) +
  scale_x_continuous(limits = c(-15,15)) + 
  scale_y_continuous(limits = c(-10, 10)) + 
  labs(title = "Preference Utility with Multiple Actors in Multidimensional Space", 
       x = "Preference Dimension 1",
       y = "Preference Dimension 2") + 
  theme_minimal()
```


